### ISSUE TITLE
Apple Photos too?

### ISSUE THREAD

**Issue by Daniel15** [jensb/iphoto2xmp#1]
Hello!
I found this project while searching Google for a way to export photos from iPhoto. I haven't had a chance to try it yet, but I was just wondering whether your script works for Apple's "Photos" app as well, or just for iPhoto? I took a quick look and Photos appears to use the same database structure as iPhoto. I haven't looked too far into it yet though.

Thanks!

**Comment by jensb** [comment]
I haven't tried out Photos. I saw it and directly moved on to Digikam (digikam.org) ... Please try, if there are issues, report here. I'll help if I can. I wouldn't be surprised if Apple changed the DB structure a little though ... some items are really stored in weird places with iPhoto, _I_ would change it if I could.

**Comment by Daniel15** [comment]
So I tried it and this happened:

```
iphoto2xmp.rb:66:in `size': No such file or directory @ rb_file_s_size - C:/Users/Daniel/Pictures/Photos Library.photoslibrary/Previews/2014/08/17/20140817-122954/R3fsE+PnTPuhxlrna299HQ/DSC00018.JPG (Errno::ENOENT)
        from iphoto2xmp.rb:66:in `link_photo'
        from iphoto2xmp.rb:331:in `block in <main>'
        from iphoto2xmp.rb:313:in `each'
        from iphoto2xmp.rb:313:in `<main>'
```

There's no copy of `DSC00018.JPG` in the `Previews` directory, I only see it in `Thumbnails` and `Master`.

**Comment by jensb** [comment]
OK .. would it work if you (temporarily, with a copy of your library maybe) renamed Thumbnails to Previews? Is it just the directory name?

**Comment by Daniel15** [comment]
It did already have a folder called "Previews", except not all files seem to be in there (in fact it was quite empty). I deleted the "Previews" directory and copied "Thumbnails" to "Previews".

I encountered this error:

```
(erb):29:in `concat': incompatible character encodings: IBM437 and UTF-8 (Encoding::CompatibilityError)
```

Which is apparently fixed by running `chcp 65001`. I'm on Windows, which does not default to UTF-8 at the console.

Next I encountered this error:

```
iphoto2xmp.rb:360:in `block in <main>': undefined method `sqlclean' for nil:NilClass (NoMethodError)
        from iphoto2xmp.rb:319:in `each'
        from iphoto2xmp.rb:319:in `<main>'
```

Which I avoided by reverting 81f978c04e350a312ca6deb790564053ae6fc179  locally.

After fixing those two issues, it actually worked for quite a few of my albums! They were nicely sorted into one folder per album, which is exactly what I wanted.

However, once it got around 60% through my library, it failed with this error:

```
iphoto2xmp.rb:460:in `block (2 levels) in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
        from iphoto2xmp.rb:458:in `each'
        from iphoto2xmp.rb:458:in `inject'
        from iphoto2xmp.rb:458:in `block in <main>'
        from iphoto2xmp.rb:318:in `each'
        from iphoto2xmp.rb:318:in `<main>'
```

Which is this line:

```
h[album['modelId'].to_i]['path'] = "#{folderlist[album['f_id']]['folderPath']}/#{album['name']}"
```

My guess is that `album['f_id']` is null, but I don't know enough about Ruby to debug it :(

**Comment by jensb** [comment]
I will set up a Photos DB over the next weekend and have a look at it. Thank you!

**Comment by dmd** [comment]
https://github.com/patrikhson/photo-export/ seems to be a thing as well; I haven't tried it yet. I'd really like to see something that works!

**Comment by jensb** [comment]
Good point, I've contacted the author.

**Comment by Daniel15** [comment]
@dmd - Unfortunately it looks like that one uses AppleScript, so I don't think I can use it on Windows. I no longer have access to any Apple devices, I swapped my work MacBook Pro for a Lenovo X1 Yoga a few weeks ago :stuck_out_tongue:

**Comment by jensb** [comment]
I will make my script work with Photos too (otherwise it has only a small future - Apple is basically forcing everybody to convert anyway). I can't give you a time frame yet though.

**Comment by dmd** [comment]
FYI everyone - if you export your photos from Photos the normal way from the file menu, it WILL actually write all the metadata to each photo's exif tag - including faces! Then you can use _exiftool_ to read it.

**Comment by Daniel15** [comment]
@dmd Does that retain album names too? I couldn't find a way to export all albums from Photos (I just saw a way to export individually selected photos), and now I don't have a Mac to try that out. I just have the photo collection.

**Comment by dmd** [comment]
No, definitely no album names. If you don't have a huge number of albums I suppose you could just go through each album, select all, export to a particular folder, and then use exiftool to write the album name as a new metadata tag.

**Comment by jensb** [comment]
This is fine for exporting a small number of images, but for my ~50'000 images spread over ~3000 events it wouldn't be practical to use. So I'll stick with my script and if there is enough interest to update it for Photos, please reopen this issue and I'll get to it.
