### ISSUE TITLE
error message mkdir': No such file or directory

### ISSUE THREAD

**Issue by gabizuquim** [jensb/iphoto2xmp#13]
Hi, I am trying to merge my pictures database with a database of biological and environmental data from the location of the pics. All I need is to get a spreadsheet with the file name from iPhoto with the keywords and descriptions of the picture. It can can csv, txt.

However, I am getting this message below (I am in MacOs Yosemite). Do you know why it is not creating a new directory? 

dyn106-43:Pictures gabzuq$ ruby iphoto2xmp.rb "~/exportMetadata" "~/Export_here"
iphoto2xmp.rb:37:in `mkdir': No such file or directory @ dir_s_mkdir - ~/Export_here (Errno::ENOENT)
	from iphoto2xmp.rb:37:in `<main>'

**Comment by jensb** [comment]
You cannot use "~", try "$HOME/Export_here" instead.
