### ISSUE TITLE
KeyError: 'List of Keywords'

### ISSUE THREAD

**Issue by mlevin77** [jensb/iphoto2xmp#14]
Running iphoto2xmp on High Sierra system, with iPhoto 9.6.1. I try

% ./prepare.py -o /Volumes/LaCie\ scratch\ disk/test/ -v ~/Pictures/iPhoto\ library/

and see this output:

photokam 0.5 - helps you convert your iPhoto 5 image library

Parsing the database...
 Opening /Users/mlevin/Pictures/iPhoto library//AlbumData.xml
Building the internal structures
 Keywords...
Traceback (most recent call last):
  File "./prepare.py", line 259, in <module>
    main()
  File "./prepare.py", line 46, in main
    keywords=data['List of Keywords']
KeyError: 'List of Keywords'

any ideas?

**Comment by jensb** [comment]
photokam is not iphoto2xmp, and only supports outdated versions of iPhoto (at least that's what it seems from reading the website).
iphoto2xmp should support any iPhoto version up to the last (before "Photos" came around). Please try iphoto2xmp.

**Comment by mlevin77** [comment]
ARGH so sorry, I somehow got the 2 packages confused, I thought I was in the iphoto2xmp folder...
