### ISSUE TITLE
Trying to compile on Ubuntu

### ISSUE THREAD

**Issue by mlevin77** [jensb/iphoto2xmp#16]
I'm trying to follow directions for Ubuntu install:

> sudo apt-get install ruby2.2 ruby2.2-dev libsqlite3-dev

I get:

% sudo apt-get install ruby2.2-dev
Reading package lists . . . Done
Building dependency tree
Reading state information . . . Done
E: unable to locate package ruby2.2-dev
E: Couldn't find any package by regex 'ruby2.2·dev'

% sudo apt-get install libsqlite3-dev
Reading package lists." Done
Building dependency tree
Reading state information . . . Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
libsqlite3-dev : Depends: libsqlite3-0 (=3.8.2-1ubuntu2.1) but 3.8.2-1ubuntu2 is to be installed
tinyos-tools : Depends: nescc but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

what am I doing wrong?

**Comment by jensb** [comment]
I'm guessing current Ubuntu doesn't have ruby 2.2 any more, it's ruby 2.5 in the meantime.
Try `sudo apt install ruby ruby-dev libsqlite3-dev`. Replace all ruby-related commands by removing the "2.2" from the command line.

Please give feedback if this works for you.

**Comment by mlevin77** [comment]
Unfortunately, no luck. Here's what I see:

$ sudo apt install ruby ruby-dev libsqlite3-dev
[sudo] password for mlevin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libsqlite3-dev : Depends: libsqlite3-0 (= 3.8.2-1ubuntu2.1) but 3.8.2-1ubuntu2 is to be installed
 ruby : Depends: ruby1.9.1 (>= 1.9.3.194-1) but it is not going to be installed
 ruby-dev : Depends: ruby1.9.1-dev (>= 1.9.3.194-1) but it is not going to be installed
 tinyos-tools : Depends: nescc but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

so then I tried

$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  kde-l10n-engb linux-headers-3.13.0-32 linux-headers-3.13.0-32-generic
  linux-image-3.13.0-32-generic linux-image-extra-3.13.0-32-generic
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  nescc
Suggested packages:
  gcc-avr gcc-msp430
The following NEW packages will be installed:
  nescc
0 upgraded, 1 newly installed, 0 to remove and 669 not upgraded.
1 not fully installed or removed.
Need to get 0 B/860 kB of archives.
After this operation, 1,605 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
(Reading database ... 268091 files and directories currently installed.)
Preparing to unpack .../nescc_1.3.4-2_amd64.deb ...
Unpacking nescc (1.3.4-2) ...
dpkg: error processing archive /var/cache/apt/archives/nescc_1.3.4-2_amd64.deb (--unpack):
 trying to overwrite '/usr/share/kde4/apps/katepart/syntax/nesc.xml', which is also in package kate-data 4:4.13.3-0ubuntu0.1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nescc_1.3.4-2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

What am I doing wrong?  thank you!!

**Comment by jensb** [comment]
There's something seriously broken with your package management.  What distribution and version are you using? You seem to have `ruby` linked to a very old Ruby version (1.9).
This works fine on Ubuntu 18.04.1 and `ruby` installs Ruby v2.5:

```
$ LANG=C sudo apt install ruby ruby-dev libsqlite3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsqlite3-dev is already the newest version (3.22.0-1).
ruby is already the newest version (1:2.5.1).
ruby-dev is already the newest version (1:2.5.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

This has also previously worked for me on Ubuntu 14.04 with Ruby 1.9, on 16.04 with Ruby 2.2 and now on 18.04 with Ruby 2.5.

**Comment by mlevin77** [comment]
ok so which package/distribution are we talking about, ruby?   I'm not even sure I have ruby installed on this machine, now that I try to figure out what version it is!  When I try to install it with sudo apt install ruby, I get:

$ LANG=C sudo apt install ruby ruby-dev libsqlite3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libsqlite3-dev : Depends: libsqlite3-0 (= 3.8.2-1ubuntu2.1) but 3.8.2-1ubuntu2 is to be installed
 ruby : Depends: ruby1.9.1 (>= 1.9.3.194-1) but it is not going to be installed
 ruby-dev : Depends: ruby1.9.1-dev (>= 1.9.3.194-1) but it is not going to be installed
 tinyos-tools : Depends: nescc but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

   I think this is a standard Ubuntu install; why won't it install the latest ruby and why is it talking about needing ruby1.9.1?  What do I do to clear up the package management and start fresh?

**Comment by jensb** [comment]
Which "standard" Ubuntu? Do  `cat /etc/issue` ; it should tell you the version.
Also send the output of `dpkg -l` , it will list all installed packages. (Attach to this bug, do not paste, it's too long)
Also send the output of `grep -ri ^deb /etc/apt/sources.list /etc/apt/sources.list.d/*list` to see what package sources you are using.

**Comment by mlevin77** [comment]
$ cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

[dpkg.txt](https://github.com/jensb/iphoto2xmp/files/2343555/dpkg.txt)

$ grep -ri ^deb /etc/apt/sources.list /etc/apt/sources.list.d/*list
/etc/apt/sources.list:deb cdrom:[Ubuntu 14.04.1 LTS _Trusty Tahr_ - Release amd64 (20140722.2)]/ trusty main restricted
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ trusty main restricted
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ trusty universe
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ trusty universe
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ trusty-security main restricted
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ trusty-security main restricted
/etc/apt/sources.list:deb http://us.archive.ubuntu.com/ubuntu/ trusty-security universe
/etc/apt/sources.list:deb-src http://us.archive.ubuntu.com/ubuntu/ trusty-security universe
/etc/apt/sources.list.d/prodoomman-qmlsaver-trusty.list:deb http://ppa.launchpad.net/prodoomman/qmlsaver/ubuntu trusty main

**Comment by mlevin77** [comment]
Ok on a completely different Ubuntu system (15.04), it also doesn't work, I see this:

$ sudo apt install ruby ruby-dev libsqlite3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-3.19.0-15 linux-headers-3.19.0-15-generic
  linux-image-3.19.0-15-generic linux-image-extra-3.19.0-15-generic
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libgmp-dev libgmpxx4ldbl libruby2.1 libyaml-0-2 ruby2.1 ruby2.1-dev
  rubygems-integration
Suggested packages:
  libgmp10-doc libmpfr-dev sqlite3-doc ri bundler
The following NEW packages will be installed
  libgmp-dev libgmpxx4ldbl libruby2.1 libsqlite3-dev libyaml-0-2 ruby ruby-dev
  ruby2.1 ruby2.1-dev rubygems-integration
0 to upgrade, 10 to newly install, 0 to remove and 14 not to upgrade.
Need to get 4,906 kB of archives.
After this operation, 22.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
WARNING: The following packages cannot be authenticated!
  libgmpxx4ldbl libyaml-0-2 libgmp-dev libsqlite3-dev rubygems-integration
  libruby2.1 ruby2.1 ruby ruby2.1-dev ruby-dev
Install these packages without verification? [y/N] y
Err http://gb.archive.ubuntu.com/ubuntu/ vivid/main libgmpxx4ldbl amd64 2:6.0.0+dfsg-6ubuntu1
  404  Not Found [IP: 91.189.88.149 80]
Get:1 http://gb.archive.ubuntu.com/ubuntu/ vivid/main libyaml-0-2 amd64 0.1.6-3 [47.6 kB]
Err http://gb.archive.ubuntu.com/ubuntu/ vivid/main libgmp-dev amd64 2:6.0.0+dfsg-6ubuntu1
  404  Not Found [IP: 91.189.88.149 80]
Err http://gb.archive.ubuntu.com/ubuntu/ vivid-updates/main libsqlite3-dev amd64 3.8.7.4-1ubuntu0.1
  404  Not Found [IP: 91.189.88.149 80]
Err http://security.ubuntu.com/ubuntu/ vivid-security/main libsqlite3-dev amd64 3.8.7.4-1ubuntu0.1
  404  Not Found [IP: 91.189.91.23 80]
Err http://gb.archive.ubuntu.com/ubuntu/ vivid/main rubygems-integration all 1.8
  404  Not Found [IP: 91.189.88.149 80]
Err http://gb.archive.ubuntu.com/ubuntu/ vivid/main libruby2.1 amd64 2.1.2-2ubuntu3
  404  Not Found [IP: 91.189.88.149 80]
Err http://gb.archive.ubuntu.com/ubuntu/ vivid/main ruby2.1 amd64 2.1.2-2ubuntu3
  404  Not Found [IP: 91.189.88.149 80]
Err http://gb.archive.ubuntu.com/ubuntu/ vivid/main ruby all 1:2.1.0.4ubuntu1
  404  Not Found [IP: 91.189.88.149 80]
Err http://gb.archive.ubuntu.com/ubuntu/ vivid/main ruby2.1-dev amd64 2.1.2-2ubuntu3
  404  Not Found [IP: 91.189.88.149 80]
Err http://gb.archive.ubuntu.com/ubuntu/ vivid/main ruby-dev all 1:2.1.0.4ubuntu1
  404  Not Found [IP: 91.189.88.149 80]
Fetched 47.6 kB in 1s (47.2 kB/s)
E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/pool/main/g/gmp/libgmpxx4ldbl_6.0.0+dfsg-6ubuntu1_amd64.deb  404  Not Found [IP: 91.189.88.149 80]

E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/pool/main/g/gmp/libgmp-dev_6.0.0+dfsg-6ubuntu1_amd64.deb  404  Not Found [IP: 91.189.88.149 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/s/sqlite3/libsqlite3-dev_3.8.7.4-1ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]

E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/pool/main/r/rubygems-integration/rubygems-integration_1.8_all.deb  404  Not Found [IP: 91.189.88.149 80]

E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/pool/main/r/ruby2.1/libruby2.1_2.1.2-2ubuntu3_amd64.deb  404  Not Found [IP: 91.189.88.149 80]

E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/pool/main/r/ruby2.1/ruby2.1_2.1.2-2ubuntu3_amd64.deb  404  Not Found [IP: 91.189.88.149 80]

E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/pool/main/r/ruby-defaults/ruby_2.1.0.4ubuntu1_all.deb  404  Not Found [IP: 91.189.88.149 80]

E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/pool/main/r/ruby2.1/ruby2.1-dev_2.1.2-2ubuntu3_amd64.deb  404  Not Found [IP: 91.189.88.149 80]

E: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/pool/main/r/ruby-defaults/ruby-dev_2.1.0.4ubuntu1_all.deb  404  Not Found [IP: 91.189.88.149 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by mlevin77** [comment]
Ok here's yet another Ubuntu variant, a clean virtual disk from OSBoxes:
[Screen Shot 2018-09-06 at 11.32.40 AM.PDF](https://github.com/jensb/iphoto2xmp/files/2357682/Screen.Shot.2018-09-06.at.11.32.40.AM.PDF)

**Comment by jensb** [comment]
Those are all terribly outdated ubuntu versions. The current version is 18.04 LTS.
This has nothing to do with my script, but anything older than 16.04 LTS will probably not even install (online) any more because the archives have been moved.
(And the archive URLs are broken, they seem to be mirrors in your case, which might be outdated or not mirror all old Ubuntu versions.)

**Comment by mlevin77** [comment]
hmmm, the latest comment I posted is from Ubuntu 18.04 LTS, from
https://www.osboxes.org/ubuntu/#ubuntu-1804-vmware 
I used their clean virtual disk (installed in VMWare and made no changes at all). Here's what fails: 
sudo gem install sqlite3

attached is what I see:
![screen shot 2018-09-07 at 5 42 07 am](https://user-images.githubusercontent.com/36042498/45211690-f31a6d00-b260-11e8-86cb-4353295850a8.jpg)
![screen shot 2018-09-07 at 5 41 47 am](https://user-images.githubusercontent.com/36042498/45211692-f3b30380-b260-11e8-9279-40946dc6eec9.jpg)
![screen shot 2018-09-07 at 5 41 06 am](https://user-images.githubusercontent.com/36042498/45211693-f3b30380-b260-11e8-8aca-80f906e036fa.jpg)

sudo gem2.5 install sqlite3 does the same thing.
This is not an old version of Ubuntu; what am I doing wrong?

**Comment by jensb** [comment]
apt install sqlite3-dev

you need the devel headers to compile the sqlite extension.

**Comment by mlevin77** [comment]
I tried, but it says Unable to locate package sqlite3-dev:
![screen shot 2018-09-09 at 8 03 34 am](https://user-images.githubusercontent.com/36042498/45264201-e768ab00-b406-11e8-8897-477116d2522a.jpg)
This is on the stock Ubuntu 18.04.1 LTS

**Comment by jensb** [comment]
sorry, it's called libsqlite3-dev. Like I mentioned in the README

**Comment by mlevin77** [comment]
Yes, I tried that also, exactly as in the README, and here's what I saw. The libsqlite3-dev installs perfectly, no problem, but then sqlite3 doesn't:
![screen shot 2018-09-09 at 7 49 10 pm](https://user-images.githubusercontent.com/36042498/45270267-78706e00-b469-11e8-8189-34826e790515.jpg)

**Comment by jensb** [comment]
OK. So I just installed an Ubuntu 18.04.1 "minimal" desktop on a Virtualbox host.
And I could actually reproduce your errors.
On a virgin system, you also need a C compiler to create sqlite3 binaries for Ruby.
`sudo apt install gcc make` 

I added this to the instructions (d5097a0e75). I have never seen a Linux system that didn't have at least an essential build system set up (Debian and Ubuntu even have the virtual package `build-essential` which you can install that just pulls in all the stuff needed to compile C and C++ sources) so I didn't think about this. Sorry!

Thank you for your patience! I hope this is the last piece in the puzzle.

**Comment by mlevin77** [comment]
Thanks!! This did indeed work, it installs and runs. But it stops, I think at the same place the OS X version stops. The destination disk has room and I'm allowed to write to it. What's wrong?
![screen shot 2018-09-10 at 10 31 53 pm](https://user-images.githubusercontent.com/36042498/45334685-d1173800-b549-11e8-88a1-035e7f417813.jpg)

**Comment by jensb** [comment]
See #9 - I fixed it already.
