### ISSUE TITLE
link_photo method not working

### ISSUE THREAD

**Issue by mikeymckay** [jensb/iphoto2xmp#20]
Looks like it was checked in mid-debug:

`def link_photo(basedir, outdir, photo, imgfile, origfile)
  imgpath  = "#{basedir}/#{imgfile}"  # source image path, absolute
  if photo['rollname']
    # FIXME: just for faces debugging
    #destpath = "#{outdir}/#{photo['rotation']}/#{File.basename(imgpath)}"
    if year = parse_date(photo['roll_min_image_date'], photo['roll_min_image_tz'])
      destpath = "#{outdir}/#{year.strftime("%Y")}/#{photo['rollname']}/#{File.basename(imgpath)}"
    else
      "#{outdir}/#{photo['rollname']}/#{File.basename(imgpath)}"
    end
  else
    "#{outdir}/00_ImagesWithoutEvents/#{imgfile}"
  end
  #destpath = photo['rollname']  ?  "#{outdir}/#{photo['rollname']}/#{File.basename(imgpath)}"
  #                              :  "#{outdir}#{imgfile}"
  destdir  = File.dirname(destpath)
`

The problem is that destpath doesn't always get set. So this error gets thrown:

'dirname': no implicit conversion of nil into String (TypeError)

**Comment by jensb** [comment]
Fixed & pushed. Thanks!
