### ISSUE TITLE
Support Apple Photos

### ISSUE THREAD

**Issue by mark-in-seattle** [jensb/iphoto2xmp#22]
First, thank you (vielen dank) for the tremendous amount of work you have donated to create the iphoto2xmp script.  This has helped many iPhoto users transition to digikam and other photo management systems.

As you know Apple, being the Apple of Steve Jobs and not Steve Wosniak, changes things to suit themselves.  The iPhotos database file structure parsed by iphoto2xmp so successfully, does not, and would not be expected to parse the new Apple "Photos" database file structure.  As an Apple "Photos" user my brother's family photos are trapped in this new Apple "Photos" database structure which I am trying to help him transfer to digikam running under macOS Catalina.

If by chance you have created a version of iphoto2xmp that parses Apple "Photos" databases it would be wonderful to test that version for you against duplicate and safe to test copies of my brother's PhotoLibraries so that digikam can import his photos and report the results back to you.

I am not a Ruby coder (Assembly, C, C++, shell script), however I might attempt to modify your original iphoto2xmp script to parse the Apple "Photos" database structure, as opensource, with attribution and under the same terms as you posted this fine work.

Thank-you, from mark early in Seattle, NW corner of Vereinigte Staaten

**Comment by mark-in-seattle** [comment]
Addendum:  I was able to install a MacPorts version of Ruby v2.5 and the dependencies required by iphoto2xmp, which runs until it tries to open my brother's Apple "Photos" database with the script line:  "...librarydb = SQLite3::Database.new("#{iphotodir}/Database/apdb/Library.apdb")"   generating an error message = "...unable to open database file (SQLite3::CantOpenException)" as expected against anything other than an "iPhotos" database file structure, because Apple "Photos" does not have a Library.apdb file ...etc.

I think I could successfully test a ruby script that is aware of the Apple "Photos" database structure.

**Comment by RhetTbull** [comment]
I maintain a Python app, [osxphotos](https://github.com/RhetTbull/osxphotos), that does work with Photos and allows you to export photos along with the metadata. That might do what you need.

**Comment by RhetTbull** [comment]
@mark-in-seattle Photos doesn't have events as iPhoto did (it does have Moments which osxphotos doesn't yet handle) but here's how to get close to iphoto2xmp output using a directory structure of folders and albums as represented in Photos:

`osxphotos export /path/to/export --directory "{folder_album}" --sidecar xmp `

There's a full tutorial at the osxphotos repo.

If you really want to update iphoto2xmp to work with Photos (not for the faint of heart), I've documented the format at the [osxphotos wiki](https://github.com/RhetTbull/osxphotos/wiki)

**Comment by jensb** [comment]
Oh, wow.

osxphotos seems to have taken where I left and gone much further.
Support of current OSX versions, more documentation, more features and more everything.

Applause, and excuse me while I get my hat. :-)
