### ISSUE TITLE
Python port

### ISSUE THREAD

**Issue by RhetTbull** [jensb/iphoto2xmp#23]
Hello @jensb, I'm the author of [osxphotos](https://github.com/RhetTbull/osxphotos) which as you know performs similar functions (and more) for Photos libraries. osxphotos does not however work with iPhoto libraries. I've been working on a separate but related project ([photokit](https://github.com/RhetTbull/photokit)) where I've figured out the private Photos APIs and can now create new Photos libraries, etc. (still pre-alpha but coming along nicely).  

With Ventura, Photos no longer will import an iPhoto library which means people using Ventura that have old iPhoto libraries are stuck if they've not been previously converted.  I believe that it would be possible to use osxphotos to create a `convert-to-photos` tool to convert an iPhoto library to a new Photos library whilst preserving metadata. I'd like to use iphoto2xmp to jump start that work. However, osxphotos is licensed under MIT license and iphoto2xmp is licensed under GPL 3.0.  Would you consider allowing me to license derivative works (converting the ruby to python to work osxphotos) under MIT license?

**Comment by jensb** [comment]
Of course.
Initially I chose GPL3 to prevent Apple from taking my script and making it a paid service :-D but I think this risk has become smaller with time.

**Comment by RhetTbull** [comment]
Great -- thanks! I'll include credit to you & iphoto2xmp in the osxphotos License.

**Comment by RhetTbull** [comment]
Python port is complete.[osxphotos](https://github.com/RhetTbull/osxphotos)  as of [v0.64.0](https://github.com/RhetTbull/osxphotos/releases/tag/v0.64.0) can now export iPhoto libraries with all metadata including sidecars. It does not export the binary edit information that iphoto2xmp did nor create any of the other Digikam sqlite databases but it can export the photos and all metadata.  For example:

`osxphotos export /path/to/export --library /path/to/iPhoto\ Library.photolibrary --directory "{folder_album}" --sidecar xmp`
