### ISSUE TITLE
no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by erkcan** [jensb/iphoto2xmp#3]
I am trying the code on OSX Yosemite, using its default ruby (sadly it is older than Ruby 2.1 that is mentioned in the source code):
$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

The only requirement that I had to install explicitly was progressbar, which I did with sudo gem install progressbar.

When I try to run the code, I get the following output:
$ ruby iphoto2xmp.rb "/Users/erkcan/Pictures/iPhoto Library" /Users/erkcan/Pictures/DigiKamFamilyLibrary
iphoto2xmp.rb:250:in `[]': no implicit conversion of String into Integer (TypeError)
        from iphoto2xmp.rb:250:in`block in <main>'
        from iphoto2xmp.rb:249:in `open'
        from iphoto2xmp.rb:249:in`<main>'

I looked at the code, but I have zero prior experience with Ruby, so could not debug the issue. Any ideas?

**Comment by jensb** [comment]
Sorry, that couldn't have worked. My test library has no event notes since it has been upgraded to iPhoto 9.6. Please try again and report if it worked. Thanks!

**Comment by erkcan** [comment]
Thanks, it does seem to work now. By the way, I also had upgraded to iPhoto 9.6 - it claims to be version 9.6(910.29), but I guess something was not ok with it.

(One thing that is not yet working for me is that no faces appear to be tagged in digikam after the export, but I can see the relevant pieces of data in the xmp files. This is probably an issue on the digikam side, I will explore.)
